pimcore:
    objects:
        custom_layouts:
            definitions:
                6daad641-862b-4b2e-aac9-ac5152d38706:
                    id: 6daad641-862b-4b2e-aac9-ac5152d38706
                    name: test
                    description: ''
                    creationDate: 1696487067
                    modificationDate: 1696487421
                    userOwner: 2
                    classId: '3'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: ''
                                title: ''
                                width: 0
                                height: 0
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: Base
                                        type: null
                                        region: west
                                        title: ''
                                        width: 0
                                        height: 0
                                        collapsible: false
                                        collapsed: false
                                        bodyStyle: ''
                                        datatype: layout
                                        children:
                                            -
                                                name: geographic
                                                title: Geographic
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: block
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                lazyLoading: false
                                                disallowAddRemove: false
                                                disallowReorder: false
                                                collapsible: false
                                                collapsed: false
                                                maxItems: null
                                                styleElement: ''
                                                children:
                                                    -
                                                        name: coordinates
                                                        title: Coordinates
                                                        tooltip: ''
                                                        mandatory: false
                                                        noteditable: false
                                                        index: false
                                                        locked: false
                                                        style: ''
                                                        permissions: null
                                                        fieldtype: geopoint
                                                        relationType: false
                                                        invisible: false
                                                        visibleGridView: false
                                                        visibleSearch: false
                                                        lat: 0
                                                        lng: 0
                                                        zoom: 1
                                                        mapType: roadmap
                                                        height: 180
                                                        width: ''
                                                        datatype: data
                                                    -
                                                        name: bounds
                                                        title: Bounds
                                                        tooltip: ''
                                                        mandatory: false
                                                        noteditable: false
                                                        index: false
                                                        locked: false
                                                        style: ''
                                                        permissions: null
                                                        fieldtype: geobounds
                                                        relationType: false
                                                        invisible: false
                                                        visibleGridView: false
                                                        visibleSearch: false
                                                        lat: 0
                                                        lng: 0
                                                        zoom: 1
                                                        mapType: roadmap
                                                        height: 180
                                                        width: ''
                                                        datatype: data
                                                    -
                                                        name: polygon
                                                        title: Polygon
                                                        tooltip: ''
                                                        mandatory: false
                                                        noteditable: false
                                                        index: false
                                                        locked: false
                                                        style: ''
                                                        permissions: null
                                                        fieldtype: geopolygon
                                                        relationType: false
                                                        invisible: false
                                                        visibleGridView: false
                                                        visibleSearch: false
                                                        lat: 0
                                                        lng: 0
                                                        zoom: 1
                                                        mapType: roadmap
                                                        height: 180
                                                        width: ''
                                                        datatype: data
                                                    -
                                                        name: polyline
                                                        title: Polyline
                                                        tooltip: ''
                                                        mandatory: false
                                                        noteditable: false
                                                        index: false
                                                        locked: false
                                                        style: ''
                                                        permissions: null
                                                        fieldtype: geopolyline
                                                        relationType: false
                                                        invisible: false
                                                        visibleGridView: false
                                                        visibleSearch: false
                                                        lat: 0
                                                        lng: 0
                                                        zoom: 1
                                                        mapType: roadmap
                                                        height: 180
                                                        width: ''
                                                        datatype: data
                                                layout: null
                                                datatype: data
                                            -
                                                name: fund
                                                title: Fund
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: consent
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: 0
                                                width: ''
                                                datatype: data
                                            -
                                                name: dept
                                                title: Dept
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: classificationstore
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                children: {  }
                                                labelWidth: 0
                                                localized: false
                                                storeId: 1
                                                hideEmptyData: false
                                                disallowAddRemove: false
                                                fieldDefinitionsCache: null
                                                allowedGroupIds: {  }
                                                activeGroupDefinitions: {  }
                                                maxItems: 8
                                                height: null
                                                width: null
                                                datatype: data
                                        locked: false
                                        fieldtype: tabpanel
                                        border: false
                                        tabPosition: top
                                    -
                                        name: More
                                        type: null
                                        region: center
                                        title: ''
                                        width: 0
                                        height: 0
                                        collapsible: false
                                        collapsed: false
                                        bodyStyle: ''
                                        datatype: layout
                                        children:
                                            -
                                                name: students
                                                title: Students
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: numericRange
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                integer: false
                                                unsigned: false
                                                minValue: null
                                                maxValue: null
                                                decimalSize: null
                                                decimalPrecision: null
                                                width: ''
                                                datatype: data
                                            -
                                                name: faculty
                                                title: Faculty
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: manyToOneRelation
                                                relationType: true
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                classes:
                                                    -
                                                        classes: Faculty
                                                displayMode: grid
                                                pathFormatterClass: ''
                                                assetInlineDownloadAllowed: false
                                                assetUploadPath: ''
                                                allowToClearRelation: true
                                                objectsAllowed: true
                                                assetsAllowed: false
                                                assetTypes: {  }
                                                documentsAllowed: false
                                                documentTypes: {  }
                                                width: ''
                                                datatype: data
                                        locked: false
                                        fieldtype: panel
                                        layout: null
                                        border: false
                                        icon: ''
                                        labelWidth: 100
                                        labelAlign: left
                                locked: false
                                fieldtype: region
                                icon: ''
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
