demo:
    resource: "@DemoBundle/src/Controller/"
    type:     annotation
    prefix:   /

product_preview:
    path: /preview/product
    controller: DemoBundle\Controller\ProductPreviewController::previewProductAction