pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    Course:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 500
                                    forceResize: false
                            -
                                method: roundCorners
                                arguments:
                                    width: 10
                                    height: 10
                            -
                                method: crop
                                arguments:
                                    width: 300
                                    height: 100
                                    x: 0
                                    'y': 131
                        medias: {  }
                        name: Course
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697006058
                        creationDate: 1696401318
                        preserveAnimation: false
