pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    shirt:
                        items: {  }
                        medias: {  }
                        name: shirt
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1695795558
                        creationDate: 1695795558
                        preserveAnimation: false
